version: '3.8'

services:
  app:
    build: .
    container_name: onvif-snapshot
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./snapshots:/app/snapshots
    restart: unless-stopped